alias g="git"
alias l="ls"
alias llr="ls -lR"
alias v="nvim"
alias nv="nvim"
alias mv="mv -i"
alias ..="cd .."
alias dc='docker-compose'
alias dcb='docker-compose build'
alias d='docker'
alias emacs='emacs -nw'
alias e='emacs'
