#!/bin/bash
DOTFILES_ROOT=$(git rev-parse --show-toplevel)

make_backup_dir() {
 if [ -d $dirname ]; then
  echo "Found existing $1, moving to $1.bk"
  mv $1 $1.bk
 fi
}

make_backup_file() {
 if [ -f $1 ]; then
  echo "Found existing $1, moving to $1.bk"
  mv $1 $1.bk
 fi
}


cd ~/
mkdir -p .config
make_backup_dir ".vim"
ln -s $DOTFILES_ROOT/.vim .

make_backup_file ".vimrc"
ln $DOTFILES_ROOT/.vimrc .

make_backup_file ".gitconfig"
ln $DOTFILES_ROOT/.gitconfig

make_backup_file ".ripgreprc"
ln $DOTFILES_ROOT/.ripgreprc

make_backup_dir ".config/fish"
ln -s $DOTFILES_ROOT/fish .config/fish

make_backup_dir ".config/nvim"
ln -s $DOTFILES_ROOT/nvim .config/nvim
