#!/bin/bash

SCRIPT_DIR=$PWD/`dirname $0`

# If directory doesnt exist
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install nvim first??

mkdir -p $SCRIPT_DIR/undo
mkdir -p $SCRIPT_DIR/session

if [ -d "$HOME/.config/nvim/" ]; then
  echo "Found existing .config/nvim, moving to .config/nvim.bk"
  mv $HOME/.config/nvim $HOME/.config/nvim.bk
fi
ln -s $PWD/`dirname $0` $HOME/.config/nvim

# Need conditions here
pip3 install pynvim

# Need conditions here as well
nvim +PlugInstall +qall
nvim +UpdateRemotePlugin +qall
